services:

  postgres:
    image: postgres:17
    container_name: seat-reservation-postgres

    environment:
      POSTGRES_DB: seat_reservation
      POSTGRES_USER: seat_user
      POSTGRES_PASSWORD: seat_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: