spring:
  application:
    name: seat-reservation

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/seat_reservation}
    username: ${DB_USERNAME:seat_user}
    password: ${DB_PASSWORD:seat_password}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}